spring.application.name=call-orchestration-service
server.servlet.context-path=/call-orchestration-service/
server.port=8086

spring.config.import=optional:file:./configs/service.properties,optional:file:./secrets/secrets.properties

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=calls

spring.flyway.enabled=true
spring.flyway.schemas=calls
spring.flyway.default-schema=calls
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

server.forward-headers-strategy=native